### ISSUE TITLE
CR Calc page missing features

### ISSUE THREAD

**Issue by TheGiddyLimit** [astranauta/astranauta.github.io#205]
from @Temp345

"The CR Calc page is missing some monster features, after Superior Invisibility it should also list:
Surprise Attack with field to specify additional dmg/round (counted only for 1 round, not 3)
Swallow with field to specify dmg/round (assume the mob swallows 1 creature and deals 2 rounds of acid damage)
Undead Fortitude +effectiveHp based on CR:
CR1-4=7hp;
CR5-10=14hp;
CR11-16=21hp;
CR17+=28hp
Web: +1 effective AC
Wounded Fury with field to specify dmg/round
(See DMG pag. 281)
Probably calculating the effective damage (as average of 3 rounds) could be tricky."

**Comment by MrLabRat** [comment]
Isn't Relentless is the same as Undead Fortitude?

**Comment by TheGiddyLimit** [comment]
From memory, the feature isn't the same - Undead Fortitude doesn't work against radiant damage or crits (headshots vs zombies!).

I can't check what that equates to in CR terms at the moment, though.

**Comment by astranauta** [comment]
Most likely barely negligible. For most intents and purposes, the features are interchangeable, so it doesn't really matter whether we miss a specific version of it. Backburnered.

**Comment by Temp345** [comment]
Yes, Relentless and Undead Fortitude have the same effect on the effective hp.
I apologize for not noticing that. But maybe the label of the checkbox could be
"Relentless or Undead Fortitude" to make it more clear?

You probably know better than me, but please be careful with **Surprise Attack** and **Swallow**
as they don't take effect for 3 rounds, but only for 1 (Surprise Attack) and for 2 rounds, so calculating the damage/round as average for 3 rounds is tricky (can't simply add 1/3 or 2/3 of the value
specified in the input field to the effective damage).

The guideline seems to calculate the **Wounded Fury** extra damage as average for 3 rounds,
even if it is unlikely that a creature would survive so long. Eh, I guess there's no need to be fastidious there.

**Comment by astranauta** [comment]
Yeah, probably. Throw it on the pile, I guess.
As for Surprise Attack, couldn't you just add the flat damage? It should still factor in, otherwise I need to re-attend my math courses. And Swallow, hm... I don't think it's an attack that should be considered for it. Mostly because Swallow is a trait of the monster, a special move, not their most damaging attack. It's worth consideration, sure, but it's not the most important thing. Surprise Attack should probably be added though, along with Wounded Fury.

**Comment by Temp345** [comment]
I agree that these are not super important and I don't want to be pedantic,
but just for the sake of argument...

## Surprise Attack
The Bugbear does on average 11 damage with its morningstar.
On 3 rounds it does 33 damage, so its damage/round is 33/3=11.

On the first round (we have to imagine the best scenario, so it surprises its target),
it can do an extra 7 damage (on average).

So at best the Bugbear can do 18+11+11 on the first 3 rounds, on average **13** dmg/round.
If you simply add 7 to the average damage/round you get (18+18+18)/3 = **18** dmg/round.
(Note that in this specific case the final CR doesn't change using 13 or 18)

## Swallow
I guess it depends case by case.

Example: Remorhaz (ignoring the Heated Body trait to keep calculations simpler)
1st round: bite 50
2nd round: swallow 50 (it includes a bite attack)
3rd round: 21 to swallowed target, bite 50 (to another target)
Average: (50+50+71)/3 = 57 dmg/round (better than only using its bite)

The purple worm - who doesn't have that trait by the way - can increase its dmg/round with Swallow
(which is not an indipendent action, it's included with the bite)

**Comment by TheGiddyLimit** [comment]
@Temp345 Don't worry about these lazy fools, it'll get done. Eventually.

Alternatively, you could update it yourself. I believe the data for this is [monsterfeatures.json](https://raw.githubusercontent.com/astranauta/astranauta.github.io/master/data/monsterfeatures.json).

**Comment by Temp345** [comment]
A little OT, but I'll report it here instead of opening a new one.

There's something wrong with the input-fields related to the following data/features:
- Hit Dice
- Legendary Resistances
- Regeneration

![screenshot](https://user-images.githubusercontent.com/32430518/31306420-2a5bf4be-ab50-11e7-9467-9e3e0069a230.png)

The input-field is too small and it's hard to read the number.

**Note**: this happens on Firefox, not on Chromium (but in the latter there are no up and down arrows to increase/decrease the value).
I guess it's a problem with the html or the css, I tried to fix it on a local copy
but I'm not very familiar with it.

**Comment by TheGiddyLimit** [comment]
@Temp345 HD box fixed in #228, to be merged when someone else wakes up.

As an aside, lease refrain from raising unrelated issues in the comments, you're allowed to open another issue.

**Comment by Temp345** [comment]
I added some missing features. If my changes get approved and I didn't make
any mistake this issue can be closed.

As already discussed here, some missing features can't be added because they
add damage only on 1 or 2 turns, so you can't add a flat number to the average dpr.
The average has to be calculated specifically and used in the dpr input field.
The note at the bottom of the CR Calc page should already cover that.

Some, like **Martial Advantage** (Hobgoblin), could be indeed added, but they can 
be easily included directly in the input fields. Sneak Attack for example
is not included in the list of CR altering features in the DMG (well, probably also
because it's not a monster-only feature).

**Rampage** (Gnoll) seems very situational and specific for gnolls
(seems like it adds half of the bite average damage to the dpr).

Other features are already included in the stat block (e.g. **Fiendish Blessing**)
so they should be included in the related input fields for AC, damage, etc.

**Comment by Temp345** [comment]
I repeat here what I wrote in the pull request comment.

I just noticed that **Constrict** includes **Giant Spider** as example creature, this can be removed
since I've added **Web** (that has the same effect) and use only **Giant Constrictor Snake** as
example (there's no "Giant Snake").

Other features that could be added since they add a flat number to the DRP:
**Enlarge** (Duergar), but I usually find more handy to add the extra damage directly to the DPR input field.
**Martial Advantage** (Hobgoblin), see previous comment.
**Pounce** (Tiger) in theory, but realistically this works only on the first turn (or only for 1 turn
anyway), since it sounds weird to take an AoO in order to use it again (unless the attack disables
the target and that could maybe considered to be the optimal scenario in which many of these
features are taken into account).
**Rampage** (Gnoll) seems also very specific and situational.

**Comment by Temp345** [comment]
Damn it.
I just noticed that **Heated Body** adds the damage specified in the field 3 times to the DPR.
Would using **trait * 0.33** fix this without loss of precision due to approximation?
Is there a better way to do it? I better leave that to someone who knows how it works internally.

**Comment by DBAWiseMan** [comment]
Now that it's been merged, I've added in **Angelic Weapons**, **Enlarge**, and **Martial Advantage**, and updated the example for **Constrict**. I believe that will then cover everything we can currently handle from DMG. I aim to create a PR later today to cover this and all the HTML/js changes.
Are you sure it's adding 3 times?
I'm seeing different behaviour, e.g. RESET, then choose CR 4 (to get average DPR of 27), then click on Heated Body (keeping the value 0) and average DPR then becomes 270. Setting the value to 11 you get an average DPR of 2711. In other words it's adding two strings of numbers, e.g. "27" and "11" rather than adding two numbers and then making it a string.
I don't think we need to change the entry in the JSON, but I will look at fixing the code

**Comment by TheGiddyLimit** [comment]
Confirmed. Someone forgot to use `Number()`? I'll leave it in your capable hands.
