### ISSUE TITLE
Bestiary: filter by type

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#234]
Is there a better way to handle the filtering by type?

If I put "aberrations" I'd like to see also all the slaads and not only
the one without the shapechanger tag. This is just an example,
it happens with a lot of monsters types.

Is introducing tags (for things like shapechanger, titan, etc) too much work?

The sub categories for humanoids make sense, but selecting "humanoid"
should list them all. Right now just the lonely Sea Spawn is there.

Sorry if this sounds like a feature request, it's just an observation.

**Comment by TheGiddyLimit** [comment]
I'll handle it when I do #237, after the prerequisite #236 gets merged. I'll be taking a look at filters across the site, so this is a prime time to log issues.

As an aside, there's nothing wrong with feature requests. Obviously, it's preferred that you code the feature yourself, but that's not always practical.

**Comment by DBAWiseMan** [comment]
I'm working on a proof-of-concept where I've split the "type" into "type", "tags", and "source", so there would only be a handful of different types, tags, and sources, e.g.
"source": "Plane Shift Kaladesh", "source": "Plane Shift Zendikar", "source": "storm kings thunder",
"tags": "(any race)", "tags": "(shadow fey)", "tags": "(shapechanger)", "tags": "(shapechanger, nkosi)", "tags": "(shapechanger, titan)", "tags": "(subek)", "tags": "(titan)",
"type": "aberration", "type": "beast", "type": "celestial",
[naturally this is just a few of the slightly longer list]

It also simplifies page-bestiary (currently only changed in my POC and set-up to work with everything else without any change), e.g. here's the rows I've changed:

	// parse all the monster data
	for (var i = 0; i < monsters.length; i++) {
		var name = monsters[i].name;
		var source = monsters[i].source;
		var origsource = parsesourcename(source);
		var type = monsters[i].type;
		var tags = "";
		if (!(monsters[i].tags === undefined)) {
			tags = monsters[i].tags;
			type += " "+tags;
		}
		source = parsesource(source);

I'm back at work tomorrow, but will have another look this weekend (assuming it's compatible with TheGiddyLimit's JSON re-vamp). I'm hoping it won't be too difficult to add in another column in the HTML & js to separate the types and tags. Assuming that's the case then it should fit the request. Filtering by individual tag might not be trivial but at least we'd have the tags separated-out as their own JSON property (which might need tweaking so that each tag entry is an array element).

**Comment by TheGiddyLimit** [comment]
I have something similar in the JSON revamp, if slightly more granular. The other half of the problem is allowing the user to easily filter, which I plan to use the new (see psionics page) filter interface to accomplish.

As an aside, we ought to coordinate more, this is the sort of duplication of effort we could be avoiding.

**Comment by TheGiddyLimit** [comment]
This is now live.
