### ISSUE TITLE
I want to give you money for this.

### ISSUE THREAD

**Issue by taylregriffin** [astranauta/astranauta.github.io#63]
Your website is amazing and me and all my players use it.  I just used your Roll20 tool to import monsters and I'm fucking blown away. And it seems to do all sorts of other neato things as well. Could you set up a patreon or paypal or something so we can make donations?

**Comment by Buluphont** [comment]
I left this for @astranauta because he's been in charge of the continuation but seeing how he hasn't replied here yet, I'll try and speak for us -- anybody, please chime in if you wish.

Flattered we are, but this is merely a continuation and maintenance of someone else's good work. I personally don't think it'd be right to take money for it (and actually, taking money for this work probably puts the project at higher risk of being besieged by WotC legal anyhow).

Thank you for the praise, I'll forward it to the team and make sure everyone sees it, along with the original project's maintainer.

**Comment by AndyLampert** [comment]
Ditto. I came here to say the same thing, but if it does increase the chances of it being seized, I would beg you do whatever is in your power for that not to happen; this is the best 5E resource on the web by leaps and bounds.

**Comment by astranauta** [comment]
Officially, I cannot accept this because the work we're doing is copyright infringement and that's what caused the original hoster to throw in their hat. I would hate to recieve a letter from Wizards stating that I would have to take the site down or legal action would be pursued against me, but that's what I'm risking right now, so I'm glad to hear that people are using the tool. That's what it's there for, at least. Also, as Buluphont said, we're deeply flattered that you seem to think that we're important enough to donate to. So thank you, and keep being awesome. I appreciate the thought, and the team appreciates the thought, but it's simply not something that we can accept. The best way to show your appreciation would simply be to use it or even contribute if you want. Thanks again, and sorry, because this probably isn't the answer you wanna hear.

Have a great day. It's on us.

**Comment by Jeb-DELETE-THIS-ACCOUNT-EVENTUALLY** [comment]
As the one currently adding Suggested Characteristics for backgrounds, I am happy you're finding this resource so useful and hope that you can continue to do so for the remainder of Fifth Edition's life cycle.

**Comment by taylregriffin** [comment]
Thank you so much for doing this work out of the good of your heart then. If I can't give you money, then can I do data entry to help you out? I've seen the format of the .json entries, I could probably put more monsters or spells in that format if you need me to. Of course, you've probably got a script for that. :)

**Comment by taylregriffin** [comment]
Well, thank you so much for doing this out of the good of your heart then.
